// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Application struct {
	ID   string             `json:"id"`
	Slug string             `json:"slug"`
	Name *TranslationString `json:"name"`
}

type TranslationString struct {
	En string `json:"en"`
}
